In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/teamup_synthetic_dataset.csv")

In [ ]:
df.head(10)

,user_id,professional_role,experience_level,years_experience,skills,project_interests,project_types,collaboration_goals,preferred_collaborator_skills,availability_days,availability_hours,hours_per_week,preferred_work_mode,collaboration_duration
0,TU001,Data Scientist,Beginner,1.5,SQL; Scikit-learn; Research,Social Impact,AI Prototype,Solve a real-world problem,Scikit-learn; Literature Review,Saturday,09:00-13:00,4,In-person,Flexible
1,TU002,Data Analyst,Beginner,1.4,Tableau; SQL; Data Visualization,Healthcare; FinTech,Research; Web Application,Gain practical experience,Documentation; Product Strategy; User Research,Saturday,09:00-13:00,2,Hybrid,Flexible
2,TU003,Data Scientist,Beginner,1.3,Python; SQL; Scikit-learn; Teamwork,Artificial Intelligence,Research; AI Prototype,Build a portfolio,REST APIs; Social Media; Market Research; Cont...,Monday; Wednesday; Friday,18:00-20:00,4,Hybrid,Long-term
3,TU004,UI/UX Designer,Beginner,0.5,Prototyping; User Research; Problem Solving,Productivity; Artificial Intelligence; Agricul...,Data Analysis; Dashboard; Research,Build a product,Tableau; Git; Power BI,Saturday; Sunday,14:00-17:00; 10:00-13:00,6,Remote,Flexible
4,TU005,Software Developer,Advanced,6.1,REST APIs; Testing; Python; Problem Solving; T...,Open Source,Web Application; Open Source Tool; Mobile App,Contribute to open source,Docker; Python; Testing; Wireframing,Saturday; Sunday,10:00-13:00; 14:00-17:00,8,Remote,Flexible
5,TU006,Marketing Specialist,Advanced,6.4,Content Writing; Social Media; Digital Marketi...,Artificial Intelligence; Agriculture,AI Prototype,Build a portfolio,Excel; Product Strategy; Research Design; Rese...,Saturday,09:00-13:00,4,In-person,Short-term
6,TU007,Backend Developer,Advanced,10.3,Django; Git; PostgreSQL; REST APIs,Social Impact; Public Health; Education,NaN,Learn new skills,Docker; Problem Solving,Saturday,09:00-13:00,2,In-person,Flexible
7,TU008,UI/UX Designer,Beginner,1.0,Accessibility; User Research; Wireframing; Res...,Education; Public Health,Web Application,Contribute to open source,SEO; Wireframing,Tuesday; Thursday,18:00-21:00,5,In-person,Short-term
8,TU009,Researcher,Advanced,7.4,Literature Review; Data Analysis; Teamwork,Education; Social Impact,Research,Build a product,Data Analysis; SQL; Teamwork,Saturday,09:00-13:00,2,Hybrid,Long-term
9,TU010,Software Developer,Intermediate,2.0,Git; REST APIs; Problem Solving; Research,Social Impact,Open Source Tool,Learn new skills,Teamwork; Planning,Saturday,09:00-13:00,2,In-person,Long-term

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   user_id                        100 non-null    object
 1   professional_role              100 non-null    object
 2   experience_level               100 non-null    object
 3   years_experience               100 non-null    float64
 4   skills                         100 non-null    object
 5   project_interests              100 non-null    object
 6   project_types                  98 non-null     object
 7   collaboration_goals            97 non-null     object
 8   preferred_collaborator_skills  92 non-null     object
 9   availability_days              100 non-null    object
 10  availability_hours             100 non-null    object
 11  hours_per_week                 100 non-null    int64
 12  preferred_work_mode            100 non-null    object
 13  collaboration_duration         100 non-null    object
dtypes: float64(1), int64(1), object(12)
memory usage: 11.1+ KB

In [ ]:
df.nunique()

user_id                          100
professional_role                 10
experience_level                   3
years_experience                  69
skills                           100
project_interests                 69
project_types                     76
collaboration_goals                7
preferred_collaborator_skills     92
availability_days                  5
availability_hours                10
hours_per_week                     8
preferred_work_mode                3
collaboration_duration             3
dtype: int64

In [ ]:
df.isnull().sum()

user_id                          0
professional_role                0
experience_level                 0
years_experience                 0
skills                           0
project_interests                0
project_types                    2
collaboration_goals              3
preferred_collaborator_skills    8
availability_days                0
availability_hours               0
hours_per_week                   0
preferred_work_mode              0
collaboration_duration           0
dtype: int64

In [ ]:
df["skills"] = df["skills"].fillna("").str.split("'")
(print(df["skills"].head()))

0                        [SQL; Scikit-learn; Research]
1                   [Tableau; SQL; Data Visualization]
2                [Python; SQL; Scikit-learn; Teamwork]
3        [Prototyping; User Research; Problem Solving]
4    [REST APIs; Testing; Python; Problem Solving; ...
Name: skills, dtype: object

In [ ]:
print(df.dtypes)

user_id                           object
professional_role                 object
experience_level                  object
years_experience                 float64
skills                            object
project_interests                 object
project_types                     object
collaboration_goals               object
preferred_collaborator_skills     object
availability_days                 object
availability_hours                object
hours_per_week                     int64
preferred_work_mode               object
collaboration_duration            object
dtype: object

In [ ]:
print((df== 0).sum())

user_id                          0
professional_role                0
experience_level                 0
years_experience                 1
skills                           0
project_interests                0
project_types                    0
collaboration_goals              0
preferred_collaborator_skills    0
availability_days                0
availability_hours               0
hours_per_week                   0
preferred_work_mode              0
collaboration_duration           0
dtype: int64

In [ ]:
list_cols = ["project_interests", "project_types", "collaboration_goals",
             "preferred_collaborator_skills", "availability_days"]

for col in list_cols:
    df[col] = df[col].fillna("").str.split("; ")

In [ ]:
print(df.loc[0, list_cols])

project_interests                                  [Social Impact]
project_types                                       [AI Prototype]
collaboration_goals                   [Solve a real-world problem]
preferred_collaborator_skills    [Scikit-learn, Literature Review]
availability_days                                       [Saturday]
Name: 0, dtype: object

In [ ]:
df["availability_hours"] = df["availability_hours"].fillna("").str.split(", ")
print(df.loc[3, ["availability_days", "availability_hours"]])

availability_days             [Saturday, Sunday]
availability_hours    [14:00-17:00; 10:00-13:00]
Name: 3, dtype: object

In [ ]:
all_list_cols = ["skills", "project_interests", "project_types", "collaboration_goals",
                 "preferred_collaborator_skills", "availability_days", "availability_hours"]

for col in all_list_cols:
    df[col] = df[col].apply(lambda items: [x for x in items if x != ""])

In [ ]:
print(df.loc[6, "project_types"])

[]

In [ ]:
all_skills = sorted({skill for skills in df["skills"] for skill in skills})
print(len(all_skills))
print(all_skills)

100
['Academic Writing; Statistics; Data Analysis', 'Academic Writing; Statistics; Data Analysis; Research', 'Academic Writing; Statistics; Research Design; Literature Review', 'Accessibility; Figma; Wireframing; User Research; Communication', 'Accessibility; HTML/CSS; Teamwork', 'Accessibility; UI Integration; Teamwork', 'Accessibility; User Research; Wireframing; Research', 'Accessibility; User Research; Wireframing; Usability Testing; Documentation', 'Agile; Documentation; Planning; Teamwork', 'Agile; Planning; Research', 'Agile; Project Management; Documentation', 'Agile; Risk Management; Planning; Documentation; Problem Solving', 'Analytics; Content Writing; SEO; Social Media; Documentation', 'Analytics; Digital Marketing; Content Writing; SEO; Documentation', 'Communication; Analytics; Agile', 'Communication; Documentation; Project Management', 'Content Writing; Analytics; Social Media; Digital Marketing', 'Content Writing; Market Research; SEO; Analytics; Research', 'Content Writing; SEO; Communication', 'Content Writing; SEO; Market Research; Teamwork', 'Content Writing; SEO; Social Media; Digital Marketing', 'Content Writing; Social Media', 'Content Writing; Social Media; Digital Marketing; Teamwork', 'Data Analysis; Data Collection; Literature Review; Research', 'Data Analysis; Research Design; Data Collection; Literature Review', 'Data Collection; Academic Writing; Data Analysis; Statistics; Teamwork', 'Data Collection; Academic Writing; Research Design; Literature Review', 'Data Collection; Research Design; Statistics; Academic Writing; Communication', 'Data Collection; Research Design; Statistics; Documentation', 'Data Visualization; Pandas; Machine Learning; Problem Solving', 'Digital Marketing; SEO; Content Writing; Social Media; Problem Solving', 'Django; Git; PostgreSQL; REST APIs', 'Documentation; Risk Management; Project Management; Planning; Communication', 'Git; HTML/CSS', 'Git; HTML/CSS; UI Integration; React; Documentation', 'Git; Problem Solving; Testing; Documentation', 'Git; Python; Testing; Research', 'Git; REST APIs; Problem Solving; Research', 'Git; REST APIs; Python; Research', 'Git; Testing; REST APIs; Documentation', 'Git; UI Integration; React; Problem Solving', 'HTML/CSS; UI Integration; Accessibility; React; Teamwork', 'JavaScript; Git; Research', 'Literature Review; Data Analysis; Teamwork', 'Literature Review; Statistics; Data Analysis', 'Machine Learning; Data Visualization; Pandas; Statistics', 'Machine Learning; Scikit-learn; Data Visualization; Research', 'Machine Learning; Scikit-learn; Pandas; Data Visualization; Research', 'Machine Learning; Statistics; Pandas; Scikit-learn; Research', 'Market Research; Social Media', 'Market Research; Social Media; Documentation', 'Pandas; Machine Learning; Research', 'Pandas; SQL; Data Visualization; Statistics', 'Pandas; Scikit-learn; Documentation', 'Planning; Agile', 'Planning; Communication; Project Management; Teamwork', 'Power BI; Tableau; Python; Problem Solving', 'Product Strategy; Communication; Roadmapping; Documentation', 'Product Strategy; Roadmapping; Problem Solving', 'Product Strategy; User Research; Communication; Research', 'Prototyping; Accessibility; User Research; Usability Testing; Problem Solving', 'Prototyping; User Research; Accessibility', 'Prototyping; User Research; Problem Solving', 'Python; Git; Django; Communication', 'Python; JavaScript; Problem Solving; Research', 'Python; Machine Learning; Scikit-learn; Documentation', 'Python; PostgreSQL; Problem Solving', 'Python; SQL; Scikit-learn; Teamwork', 'Python; Scikit-learn; Statistics; Communication', 'Python; Statistics; Research', 'Python; Testing; Docker; Django; Communication', 'REST APIs; Testing; Python; Problem Solving; Teamwork', 'React; Accessibility; Git; Communication', 'Risk Management; Agile', 'Risk Management; Communication', 'Risk Management; Documentation; Agile', 'Roadmapping; Analytics; Problem Solving', 'Roadmapping; User Research', 'SQL; JavaScript; Teamwork', 'SQL; REST APIs; Teamwork', 'SQL; Scikit-learn; Machine Learning; Teamwork', 'SQL; Scikit-learn; Research', 'SQL; Statistics; Python; Problem Solving', 'Scikit-learn; Statistics; Pandas; Python', 'Social Media; Analytics; Communication', 'Social Media; Analytics; Market Research', 'Social Media; Digital Marketing; Problem Solving', 'Statistics; Academic Writing; Documentation', 'Statistics; Data Visualization; Documentation', 'Tableau; Python; Data Visualization; Research', 'Tableau; Python; Problem Solving', 'Tableau; SQL; Data Visualization', 'Testing; Git; Documentation', 'Testing; Python; SQL; Documentation', 'Usability Testing; User Research; Teamwork', 'Usability Testing; User Research; Wireframing; Accessibility; Teamwork', 'User Research; Analytics', 'User Research; Usability Testing; Wireframing; Accessibility; Teamwork', 'Wireframing; Accessibility', 'Wireframing; Prototyping; User Research']

In [ ]:
print(df["skills"].iloc[0])
print(type(df["skills"].iloc[0]))
print(all_skills[:5])

['SQL; Scikit-learn; Research']
<class 'list'>
['Academic Writing; Statistics; Data Analysis', 'Academic Writing; Statistics; Data Analysis; Research', 'Academic Writing; Statistics; Research Design; Literature Review', 'Accessibility; Figma; Wireframing; User Research; Communication', 'Accessibility; HTML/CSS; Teamwork']

In [ ]:
all_skills = sorted({skill for skills in df["skills"] for skill in skills})
print(len(all_skills))
print(all_skills[:5])

100
['Academic Writing; Statistics; Data Analysis', 'Academic Writing; Statistics; Data Analysis; Research', 'Academic Writing; Statistics; Research Design; Literature Review', 'Accessibility; Figma; Wireframing; User Research; Communication', 'Accessibility; HTML/CSS; Teamwork']

In [ ]:
list_cols = ["skills", "project_interests", "project_types", "collaboration_goals",
             "preferred_collaborator_skills", "availability_days", "availability_hours"]

for col in list_cols:
    df[col] = df[col].apply(
        lambda items: [s.strip() for item in items for s in item.split(";") if s.strip()]
    )

print(len(df["skills"].iloc[0]))
all_skills = sorted({skill for skills in df["skills"] for skill in skills})
print(len(all_skills))

3
47

In [ ]:
print(df["hours_per_week"].describe())
print(df["years_experience"].describe())

count    100.000000
mean       5.020000
std        1.842155
min        2.000000
25%        4.000000
50%        5.000000
75%        6.000000
max       10.000000
Name: hours_per_week, dtype: float64
count    100.000000
mean       4.676000
std        3.635213
min        0.000000
25%        1.500000
50%        3.700000
75%        7.650000
max       11.900000
Name: years_experience, dtype: float64

In [ ]:
roles = pd.DataFrame([
    {"role_id": "R001", "project_name": "Campus Marketplace", "role_title": "UI/UX Designer",
     "required_skills": ["Wireframing", "Prototyping"], "hours_per_week": 6,
     "duration_weeks": 6, "target_level": "Intermediate",
     "topics": ["Education", "E-commerce"], "goal": "Build a portfolio", "work_mode": "Remote"},
    {"role_id": "R002", "project_name": "Campus Marketplace", "role_title": "Frontend Developer",
     "required_skills": ["HTML/CSS", "React", "UI Integration"], "hours_per_week": 8,
     "duration_weeks": 6, "target_level": "Intermediate",
     "topics": ["Education", "E-commerce"], "goal": "Build a portfolio", "work_mode": "Remote"},
    {"role_id": "R003", "project_name": "Health Info App", "role_title": "Data Analyst",
     "required_skills": ["Tableau", "Python", "Data Visualization"], "hours_per_week": 5,
     "duration_weeks": 5, "target_level": "Beginner",
     "topics": ["Healthcare", "Public Health"], "goal": "Solve a real-world problem", "work_mode": "Hybrid"},
])
print(roles)

  role_id        project_name          role_title  \
0    R001  Campus Marketplace      UI/UX Designer
1    R002  Campus Marketplace  Frontend Developer
2    R003     Health Info App        Data Analyst

                         required_skills  hours_per_week  duration_weeks  \
0             [Wireframing, Prototyping]               6               6
1      [HTML/CSS, React, UI Integration]               8               6
2  [Tableau, Python, Data Visualization]               5               5

   target_level                       topics                        goal  \
0  Intermediate      [Education, E-commerce]           Build a portfolio
1  Intermediate      [Education, E-commerce]           Build a portfolio
2      Beginner  [Healthcare, Public Health]  Solve a real-world problem

  work_mode
0    Remote
1    Remote
2    Hybrid

In [ ]:
role = roles.iloc[0]
generic = {"Teamwork", "Communication", "Problem Solving", "Research"}

needed = [s for s in role["required_skills"] if s not in generic]

def skill_share(person_skills):
    have = [s for s in needed if s in person_skills]
    return len(have) / len(needed)

df["skill_share"] = df["skills"].apply(skill_share)
print(df[["user_id", "skills", "skill_share"]].head())

  user_id                                             skills  skill_share
0   TU001                      [SQL, Scikit-learn, Research]          0.0
1   TU002                 [Tableau, SQL, Data Visualization]          0.0
2   TU003              [Python, SQL, Scikit-learn, Teamwork]          0.0
3   TU004      [Prototyping, User Research, Problem Solving]          0.5
4   TU005  [REST APIs, Testing, Python, Problem Solving, ...          0.0

In [ ]:
df["hours_ok"] = df["hours_per_week"] >= role["hours_per_week"]
print(df[["user_id", "hours_per_week", "hours_ok"]].head())
print(df["hours_ok"].sum())

  user_id  hours_per_week  hours_ok
0   TU001               4     False
1   TU002               2     False
2   TU003               4     False
3   TU004               6      True
4   TU005               8      True
35

In [ ]:
def duration_ok(pref):
    if pref == "Flexible":
        return True
    is_short_project = role["duration_weeks"] <= 6
    return is_short_project == (pref == "Short-term")

df["duration_ok"] = df["collaboration_duration"].apply(duration_ok)
print(df[["user_id", "collaboration_duration", "duration_ok"]].head())
print(df["duration_ok"].sum())

  user_id collaboration_duration  duration_ok
0   TU001               Flexible         True
1   TU002               Flexible         True
2   TU003              Long-term        False
3   TU004               Flexible         True
4   TU005               Flexible         True
64

In [ ]:
df["skills_ok"] = df["skill_share"] >= 0.5

df["fails"] = (~df["skills_ok"]).astype(int) + (~df["hours_ok"]).astype(int) + (~df["duration_ok"]).astype(int)

passed = df[df["fails"] == 0]
print(len(passed))
print(passed[["user_id", "professional_role", "skill_share", "hours_per_week"]])

3
   user_id professional_role  skill_share  hours_per_week
3    TU004    UI/UX Designer          0.5               6
62   TU063    UI/UX Designer          0.5               6
95   TU096    UI/UX Designer          0.5               6

In [ ]:
df["availability_score"] = (
    (df["hours_per_week"] / role["hours_per_week"]).clip(upper=1) + df["duration_ok"].astype(int)
) / 2

df["goals_score"] = df["collaboration_goals"].apply(lambda g: 1 if role["goal"] in g else 0)

print(df[["user_id", "availability_score", "goals_score"]].head())

  user_id  availability_score  goals_score
0   TU001            0.833333            0
1   TU002            0.666667            0
2   TU003            0.333333            1
3   TU004            1.000000            0
4   TU005            1.000000            0

In [ ]:
def prefs_score(row):
    topic_share = len(set(role["topics"]) & set(row["project_interests"])) / len(role["topics"])
    mode_match = 1 if row["preferred_work_mode"] == role["work_mode"] else 0
    return (topic_share + mode_match) / 2

levels = {"Beginner": 0, "Intermediate": 1, "Advanced": 2}

def level_score(person_level):
    gap = abs(levels[person_level] - levels[role["target_level"]])
    return {0: 1.0, 1: 0.5}.get(gap, 0.0)

df["prefs_score"] = df.apply(prefs_score, axis=1)
df["level_score"] = df["experience_level"].apply(level_score)

print(df[["user_id", "prefs_score", "level_score"]].head())

  user_id  prefs_score  level_score
0   TU001          0.0          0.5
1   TU002          0.0          0.5
2   TU003          0.0          0.5
3   TU004          0.5          0.5
4   TU005          0.5          0.5

In [ ]:
df["score"] = 100 * (
    0.35 * df["skill_share"]
    + 0.25 * df["availability_score"]
    + 0.20 * df["goals_score"]
    + 0.15 * df["prefs_score"]
    + 0.05 * df["level_score"]
)

def label(row):
    if row["fails"] == 0:
        return "Strong match" if row["score"] >= 75 else "Good match" if row["score"] >= 50 else "No match"
    if row["fails"] == 1 and row["skill_share"] > 0:
        return "Partial match"
    return "No match"

df["label"] = df.apply(label, axis=1)

result = df[df["label"] != "No match"].sort_values("score", ascending=False)
print(result[["user_id", "professional_role", "score", "label"]])

   user_id professional_role      score          label
22   TU023    UI/UX Designer  63.333333  Partial match
39   TU040    UI/UX Designer  60.416667  Partial match
3    TU004    UI/UX Designer  52.500000     Good match
41   TU042    UI/UX Designer  50.416667  Partial match
7    TU008    UI/UX Designer  46.666667  Partial match
65   TU066    UI/UX Designer  42.916667  Partial match
23   TU024    UI/UX Designer  42.500000  Partial match
94   TU095    UI/UX Designer  41.250000  Partial match

In [ ]:
def match_role(role, people):
    df = people.copy()
    needed = [s for s in role["required_skills"] if s not in generic]

    df["skill_share"] = df["skills"].apply(lambda sk: len([s for s in needed if s in sk]) / len(needed))
    df["hours_ok"] = df["hours_per_week"] >= role["hours_per_week"]
    short_project = role["duration_weeks"] <= 6
    df["duration_ok"] = df["collaboration_duration"].apply(
        lambda p: True if p == "Flexible" else short_project == (p == "Short-term"))
    df["skills_ok"] = df["skill_share"] >= 0.5
    df["fails"] = (~df["skills_ok"]).astype(int) + (~df["hours_ok"]).astype(int) + (~df["duration_ok"]).astype(int)

    availability = ((df["hours_per_week"] / role["hours_per_week"]).clip(upper=1) + df["duration_ok"].astype(int)) / 2
    goals = df["collaboration_goals"].apply(lambda g: 1 if role["goal"] in g else 0)
    topics = df["project_interests"].apply(lambda t: len(set(role["topics"]) & set(t)) / len(role["topics"]))
    mode = (df["preferred_work_mode"] == role["work_mode"]).astype(int)
    level = df["experience_level"].apply(
        lambda l: {0: 1.0, 1: 0.5}.get(abs(levels[l] - levels[role["target_level"]]), 0.0))

    df["score"] = 100 * (0.35 * df["skill_share"] + 0.25 * availability + 0.20 * goals
                        + 0.15 * (topics + mode) / 2 + 0.05 * level)
    df["label"] = df.apply(label, axis=1)

    df = df[df["label"] != "No match"].copy()
    df["order"] = df["label"].map({"Strong match": 0, "Good match": 1, "Partial match": 2})
    df = df.sort_values(["order", "score"], ascending=[True, False])
    good = df[df["order"] < 2]
    shown = good if len(good) >= 3 else df
    return shown.head(5)[["user_id", "professional_role", "score", "label"]]

for _, r in roles.iterrows():
    print("\n", r["project_name"], "/", r["role_title"])
    print(match_role(r, df))

 Campus Marketplace / UI/UX Designer
   user_id professional_role      score          label
3    TU004    UI/UX Designer  52.500000     Good match
22   TU023    UI/UX Designer  63.333333  Partial match
39   TU040    UI/UX Designer  60.416667  Partial match
41   TU042    UI/UX Designer  50.416667  Partial match
7    TU008    UI/UX Designer  46.666667  Partial match

 Campus Marketplace / Frontend Developer
   user_id   professional_role      score          label
86   TU087  Frontend Developer  61.875000  Partial match
74   TU075  Frontend Developer  61.562500  Partial match
52   TU053  Frontend Developer  39.166667  Partial match

 Health Info App / Data Analyst
   user_id professional_role      score          label
38   TU039      Data Analyst  79.583333   Strong match
78   TU079      Data Analyst  71.250000  Partial match
36   TU037      Data Analyst  68.333333  Partial match
44   TU045    Data Scientist  59.166667  Partial match
1    TU002      Data Analyst  57.083333  Partial match

 AI Study Tool / ML Engineer
   user_id professional_role      score          label
81   TU082    Data Scientist  55.833333  Partial match
30   TU031    Data Scientist  54.583333  Partial match
51   TU052    Data Scientist  53.333333  Partial match
57   TU058    Data Scientist  52.500000  Partial match
90   TU091    Data Scientist  52.083333  Partial match

 Farm Records App / Backend Developer
   user_id  professional_role      score          label
76   TU077  Backend Developer  65.833333     Good match
6    TU007  Backend Developer  45.000000  Partial match
99   TU100  Backend Developer  39.166667  Partial match

In [ ]:
df["matched_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s in sk])
df["missing_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s not in sk])
print(df[["user_id", "matched_skills", "missing_skills"]].head())

  user_id matched_skills              missing_skills
0   TU001             []  [Wireframing, Prototyping]
1   TU002             []  [Wireframing, Prototyping]
2   TU003             []  [Wireframing, Prototyping]
3   TU004  [Prototyping]               [Wireframing]
4   TU005             []  [Wireframing, Prototyping]

In [ ]:
df["matched_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s in sk])
df["missing_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s not in sk])

In [ ]:
df.head(5)[["user_id", "professional_role", "score", "label", "matched_skills", "missing_skills"]]

,user_id,professional_role,score,label,matched_skills,missing_skills
0,TU001,Data Scientist,23.333333,No match,[],"[Wireframing, Prototyping]"
1,TU002,Data Analyst,19.166667,No match,[],"[Wireframing, Prototyping]"
2,TU003,Data Scientist,30.833333,No match,[],"[Wireframing, Prototyping]"
3,TU004,UI/UX Designer,52.500000,Good match,[Prototyping],[Wireframing]
4,TU005,Software Developer,35.000000,No match,[],"[Wireframing, Prototyping]"

In [ ]:
def match_role(role, people):
    df = people.copy()
    needed = [s for s in role["required_skills"] if s not in generic]

    df["skill_share"] = df["skills"].apply(lambda sk: len([s for s in needed if s in sk]) / len(needed))
    df["hours_ok"] = df["hours_per_week"] >= role["hours_per_week"]
    short_project = role["duration_weeks"] <= 6
    df["duration_ok"] = df["collaboration_duration"].apply(
        lambda p: True if p == "Flexible" else short_project == (p == "Short-term"))
    df["skills_ok"] = df["skill_share"] >= 0.5
    df["fails"] = (~df["skills_ok"]).astype(int) + (~df["hours_ok"]).astype(int) + (~df["duration_ok"]).astype(int)

    availability = ((df["hours_per_week"] / role["hours_per_week"]).clip(upper=1) + df["duration_ok"].astype(int)) / 2
    goals = df["collaboration_goals"].apply(lambda g: 1 if role["goal"] in g else 0)
    topics = df["project_interests"].apply(lambda t: len(set(role["topics"]) & set(t)) / len(role["topics"]))
    mode = (df["preferred_work_mode"] == role["work_mode"]).astype(int)
    level = df["experience_level"].apply(
        lambda l: {0: 1.0, 1: 0.5}.get(abs(levels[l] - levels[role["target_level"]]), 0.0))

    df["score"] = 100 * (0.35 * df["skill_share"] + 0.25 * availability + 0.20 * goals
                         + 0.15 * (topics + mode) / 2 + 0.05 * level)
    df["label"] = df.apply(label, axis=1)

    df["matched_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s in sk])
    df["missing_skills"] = df["skills"].apply(lambda sk: [s for s in needed if s not in sk])

    df = df[df["label"] != "No match"].copy()
    df["order"] = df["label"].map({"Strong match": 0, "Good match": 1, "Partial match": 2})
    df = df.sort_values(["order", "score"], ascending=[True, False])
    good = df[df["order"] < 2]
    df = good if len(good) >= 3 else df
    return df.head(5)[["user_id", "professional_role", "score", "label", "matched_skills", "missing_skills"]]

In [ ]:
for _, r in roles.iterrows():
    print("\n", r["project_name"], "/", r["role_title"])
    print(match_role(r, df))

 Campus Marketplace / UI/UX Designer
   user_id professional_role      score          label  \
3    TU004    UI/UX Designer  52.500000     Good match
22   TU023    UI/UX Designer  63.333333  Partial match
39   TU040    UI/UX Designer  60.416667  Partial match
41   TU042    UI/UX Designer  50.416667  Partial match
7    TU008    UI/UX Designer  46.666667  Partial match

                matched_skills missing_skills
3                [Prototyping]  [Wireframing]
22               [Prototyping]  [Wireframing]
39  [Wireframing, Prototyping]             []
41               [Wireframing]  [Prototyping]
7                [Wireframing]  [Prototyping]

 Campus Marketplace / Frontend Developer
   user_id   professional_role      score          label  \
86   TU087  Frontend Developer  61.875000  Partial match
74   TU075  Frontend Developer  61.562500  Partial match
52   TU053  Frontend Developer  39.166667  Partial match

                       matched_skills     missing_skills
86  [HTML/CSS, React, UI Integration]                 []
74  [HTML/CSS, React, UI Integration]                 []
52                   [UI Integration]  [HTML/CSS, React]

 Health Info App / Data Analyst
   user_id professional_role      score          label  \
38   TU039      Data Analyst  79.583333   Strong match
78   TU079      Data Analyst  71.250000  Partial match
36   TU037      Data Analyst  68.333333  Partial match
44   TU045    Data Scientist  59.166667  Partial match
1    TU002      Data Analyst  57.083333  Partial match

                           matched_skills                 missing_skills
38                      [Tableau, Python]           [Data Visualization]
78  [Tableau, Python, Data Visualization]                             []
36                      [Tableau, Python]           [Data Visualization]
44                               [Python]  [Tableau, Data Visualization]
1           [Tableau, Data Visualization]                       [Python]

In [ ]:
new_roles = pd.DataFrame([
    {"role_id": "R101", "project_name": "AI Study Tool", "role_title": "ML Engineer",
     "required_skills": ["Machine Learning", "Scikit-learn", "Python"], "hours_per_week": 10,
     "duration_weeks": 8, "target_level": "Advanced",
     "topics": ["Artificial Intelligence", "Education"], "goal": "Build a product", "work_mode": "Remote"},
    {"role_id": "R102", "project_name": "Farm Records App", "role_title": "Backend Developer",
     "required_skills": ["Django", "PostgreSQL", "Docker"], "hours_per_week": 6,
     "duration_weeks": 12, "target_level": "Advanced",
     "topics": ["Agriculture"], "goal": "Build a product", "work_mode": "Remote"},
])

roles = pd.concat([roles, new_roles], ignore_index=True)
print(roles[["role_id", "role_title", "hours_per_week"]])

  role_id          role_title  hours_per_week
0    R001      UI/UX Designer               6
1    R002  Frontend Developer               8
2    R003        Data Analyst               5
3    R101         ML Engineer              10
4    R102   Backend Developer               6

In [ ]:
today = pd.Timestamp("2026-10-25")

activity = pd.DataFrame([
    {"user_id": "TU001", "last_task_update": "2026-10-24", "last_comment": "2026-10-20", "last_checkin": "2026-10-22", "away_until": None},
    {"user_id": "TU002", "last_task_update": "2026-10-15", "last_comment": "2026-10-17", "last_checkin": "2026-10-16", "away_until": None},
    {"user_id": "TU003", "last_task_update": "2026-10-10", "last_comment": "2026-10-12", "last_checkin": "2026-10-11", "away_until": "2026-10-30"},
    {"user_id": "TU004", "last_task_update": "2026-10-21", "last_comment": None, "last_checkin": None, "away_until": None},
])

for col in ["last_task_update", "last_comment", "last_checkin", "away_until"]:
    activity[col] = pd.to_datetime(activity[col])

print(activity)

  user_id last_task_update last_comment last_checkin away_until
0   TU001       2026-10-24   2026-10-20   2026-10-22        NaT
1   TU002       2026-10-15   2026-10-17   2026-10-16        NaT
2   TU003       2026-10-10   2026-10-12   2026-10-11 2026-10-30
3   TU004       2026-10-21          NaT          NaT        NaT

In [ ]:
INACTIVE_AFTER_DAYS = 5
REASSIGN_AFTER_DAYS = 7

activity["last_activity"] = activity[["last_task_update", "last_comment", "last_checkin"]].max(axis=1)
activity["days_quiet"] = (today - activity["last_activity"]).dt.days

def status(row):
    if pd.notna(row["away_until"]) and row["away_until"] >= today:
        return "Away"
    if pd.isna(row["last_activity"]) or row["days_quiet"] >= REASSIGN_AFTER_DAYS:
        return "Needs reassignment"
    if row["days_quiet"] >= INACTIVE_AFTER_DAYS:
        return "Inactive"
    return "Active"

activity["status"] = activity.apply(status, axis=1)
print(activity[["user_id", "days_quiet", "status"]])

  user_id  days_quiet              status
0   TU001           1              Active
1   TU002           8  Needs reassignment
2   TU003          13                Away
3   TU004           4              Active

In [ ]:
activity.loc[activity["user_id"] == "TU004", "last_task_update"] = pd.Timestamp("2026-10-19")

activity["last_activity"] = activity[["last_task_update", "last_comment", "last_checkin"]].max(axis=1)
activity["days_quiet"] = (today - activity["last_activity"]).dt.days
activity["status"] = activity.apply(status, axis=1)
print(activity[["user_id", "days_quiet", "status"]])

  user_id  days_quiet              status
0   TU001           1              Active
1   TU002           8  Needs reassignment
2   TU003          13                Away
3   TU004           6            Inactive

In [ ]:
def check_activity(members, today, inactive_after=5, reassign_after=7):
    df = members.copy()
    df["last_activity"] = df[["last_task_update", "last_comment", "last_checkin"]].max(axis=1)
    df["days_quiet"] = (today - df["last_activity"]).dt.days

    def status(row):
        if pd.notna(row["away_until"]) and row["away_until"] >= today:
            return "Away"
        if pd.isna(row["last_activity"]) or row["days_quiet"] >= reassign_after:
            return "Needs reassignment"
        if row["days_quiet"] >= inactive_after:
            return "Inactive"
        return "Active"

    df["status"] = df.apply(status, axis=1)
    return df[["user_id", "days_quiet", "status"]]

print(check_activity(activity, today))

  user_id  days_quiet              status
0   TU001           1              Active
1   TU002           8  Needs reassignment
2   TU003          13                Away
3   TU004           6            Inactive

In [ ]:
edge = pd.DataFrame([
    {"user_id": "E1", "last_task_update": "2026-10-20", "last_comment": None, "last_checkin": None, "away_until": None},
    {"user_id": "E2", "last_task_update": "2026-10-18", "last_comment": None, "last_checkin": None, "away_until": None},
    {"user_id": "E3", "last_task_update": None, "last_comment": None, "last_checkin": None, "away_until": None},
    {"user_id": "E4", "last_task_update": "2026-10-10", "last_comment": None, "last_checkin": None, "away_until": "2026-10-20"},
])

for col in ["last_task_update", "last_comment", "last_checkin", "away_until"]:
    edge[col] = pd.to_datetime(edge[col])

print(check_activity(edge, today))

  user_id  days_quiet              status
0      E1         5.0            Inactive
1      E2         7.0  Needs reassignment
2      E3         NaN  Needs reassignment
3      E4        15.0  Needs reassignment